;; Exercise 1.9
;; Each of the following procedures defines a method for adding two positive
;; integers in terms of the procedures `inc` and `dec`.

;; Method A
(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))

;; Method B
(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))

;; Using the substitution model, illustrate the process generated by each 
;; procedure in evaluating (+ 4 5). Are these processes iterative or recursive?

;; Method A
;; (+ 4 5)
;; (inc (+ 3 5))
;; (inc (inc (+ 2 5)))
;; (inc (inc (inc (+ 1 5))))
;; (inc (inc (inc (inc (+ 0 5)))))
;; (inc (inc (inc (inc 5))))
;; (inc (inc (inc 6)))
;; (inc (inc 7))
;; (inc 8)
;; 9
;;
;; As can be seen by the expanding and contracting form of Method A, it is apparent
;; that this method is recursive process. That is, the process builds up a chain of
;; deferred operations where each such operation maintains some state information
;; for the process. Since the amount of information stored in the chain of the
;; deferred operations grows linearly with the size of the inputs, this process
;; is referred to as a linear recursive process.

;; Method B
;; (+ 4 5)
;; (+ 3 6)
;; (+ 2 7)
;; (+ 1 8)
;; (+ 0 9)
;; 9
;;
;; In contrast to Method A, Method B is an iterative process in that the state for this
;; process is summarized by a fixed number of state variables, together with a fixed ruleset
;; describing how the process progresses through its states, and a condition determining
;; when the process should terminate. Since the number of steps grows linearly with the size 
;; of the first argument, this process is referred to as a linear iterative process.